<script setup>
import { ref, onMounted, computed } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { useStore } from 'vuex'
import Utils from '../config/utils'
import athleteServices from '../services/athleteServices'
import goalServices from '../services/goalServices'
import exerciseServices from '../services/exerciseServices'
import exercisePlanServices from '../services/exercisePlanServices'

const router = useRouter()
const route = useRoute()
const store = useStore()

const user = ref(null)
const currentUser = computed(() => store.state.currentUser || store.state.loginUser)

const athleteId = computed(() => route.params.id)

const athlete = ref({
  user_id: null,
  first_name: '',
  last_name: '',
  email: '',
  age: null,
  gender: '',
  team: '',
  sport_type: '',
  totalWorkouts: 0,
  bio: ''
})

const activeTab = ref('goals')
const goals = ref([])
const workoutResults = ref([])
const athleteAssignedPlans = ref([])
const availablePlans = ref([])
const showAssignPlanDialog = ref(false)
const showRemovePlanDialog = ref(false)
const showDeleteGoalDialog = ref(false)
const planToRemove = ref(null)
const goalToDelete = ref(null)
const selectedPlanId = ref(null)
const loading = ref(true)
const error = ref(null)
const successMessage = ref(null)

// Goal creation
const showAddGoalDialog = ref(false)
const coachPlans = ref([])
const selectedPlanForGoal = ref(null)
const exercisesFromPlan = ref([])
const selectedExerciseForGoal = ref(null)
const loadingExercises = ref(false)

const newGoal = ref({
  planId: null,
  exerciseId: null,
  exerciseName: '',
  targetValue: null,
  currentValue: 0,
  unit: 'reps',
  description: '',
  targetDate: '',
  timeframe: 'week'
})

const unitOptions = [
  { title: 'Reps', value: 'reps' },
  { title: 'Weight (lbs)', value: 'lbs' },
  { title: 'Weight (kg)', value: 'kg' },
  { title: 'Time (minutes)', value: 'minutes' },
  { title: 'Distance (miles)', value: 'miles' },
  { title: 'Distance (km)', value: 'km' }
]

const timeframeOptions = [
  { title: 'This Week', value: 'week' },
  { title: 'This Month', value: 'month' },
  { title: 'Custom Date', value: 'custom' }
]

const autoGeneratedTitle = computed(() => {
  if (!selectedExerciseForGoal.value || !newGoal.value.targetValue) {
    return ''
  }
  
  const exercise = exercisesFromPlan.value.find(ex => ex.id === selectedExerciseForGoal.value)
  const exerciseName = exercise?.name || 'Exercise'
  
  return `${exerciseName}: ${newGoal.value.targetValue} ${newGoal.value.unit}`
})

const computedTargetDate = computed(() => {
  if (newGoal.value.timeframe === 'custom') {
    return newGoal.value.targetDate
  }
  
  const today = new Date()
  
  if (newGoal.value.timeframe === 'week') {
    const daysUntilSunday = 7 - today.getDay()
    today.setDate(today.getDate() + daysUntilSunday)
  } else if (newGoal.value.timeframe === 'month') {
    today.setMonth(today.getMonth() + 1, 0)
  }
  
  return today.toISOString().split('T')[0]
})

const exercises = ref([])

const showSuccess = (message) => {
  successMessage.value = message
  setTimeout(() => {
    successMessage.value = null
  }, 3000)
}

const fetchAthleteData = async () => {
  try {
    loading.value = true
    error.value = null
    
    const response = await athleteServices.getAthleteById(athleteId.value)
    athlete.value = response.data
    
  } catch (err) {
    if (err.response?.status === 401) {
      error.value = 'Session expired. Please log in again.'
      setTimeout(() => router.push('/'), 2000)
    } else {
      error.value = 'Unable to load athlete data. Please try again.'
    }
  } finally {
    loading.value = false
  }
}

const fetchAthleteGoals = async () => {
  try {
    const response = await goalServices.getGoalsByAthlete(athleteId.value)
    goals.value = response.data
  } catch (err) {
    if (err.response?.status === 401) {
      router.push('/')
    }
  }
}

const fetchAthleteResults = async () => {
  try {
    const response = await exerciseServices.getAthleteResultsForCoach(athleteId.value)
    workoutResults.value = response.data
  } catch (err) {
    if (err.response?.status === 401) {
      router.push('/')
    }
  }
}

const loadExercises = async () => {
  try {
    const response = await exerciseServices.getAllExercises()
    exercises.value = response.data
  } catch (err) {
    // Silently fail
  }
}

const fetchAthleteAssignedPlans = async () => {
  try {
    const response = await exercisePlanServices.getPlansByAthlete(athleteId.value)
    athleteAssignedPlans.value = response.data
  } catch (err) {
    // Silently fail
  }
}

const loadAvailablePlans = async () => {
  try {
    const response = await exercisePlanServices.getAllExercisePlans()
    availablePlans.value = response.data
  } catch (err) {
    error.value = 'Unable to load training plans'
  }
}

const loadCoachPlans = async () => {
  try {
    const response = await exercisePlanServices.getAllExercisePlans()
    coachPlans.value = response.data
  } catch (err) {
    error.value = 'Unable to load training plans'
  }
}

const onPlanSelected = async () => {
  if (!selectedPlanForGoal.value) {
    exercisesFromPlan.value = []
    selectedExerciseForGoal.value = null
    return
  }
  
  try {
    loadingExercises.value = true
    const response = await goalServices.getExercisesFromPlan(selectedPlanForGoal.value)
    exercisesFromPlan.value = response.data
    
    if (exercisesFromPlan.value.length > 0) {
      selectedExerciseForGoal.value = exercisesFromPlan.value[0].id
    }
  } catch (err) {
    error.value = 'Unable to load exercises from plan'
  } finally {
    loadingExercises.value = false
  }
}

const openAssignPlanDialog = () => {
  loadAvailablePlans()
  showAssignPlanDialog.value = true
}

const closeAssignPlanDialog = () => {
  showAssignPlanDialog.value = false
  selectedPlanId.value = null
}

const assignPlan = async () => {
  if (!selectedPlanId.value) {
    error.value = 'Please select a plan'
    return
  }

  try {
    await exercisePlanServices.assignPlanToAthlete(selectedPlanId.value, athleteId.value)
    showSuccess('Training plan assigned successfully')
    await fetchAthleteAssignedPlans()
    closeAssignPlanDialog()
  } catch (err) {
    error.value = err.response?.data?.message || 'Unable to assign plan. Please try again.'
  }
}

const confirmUnassignPlan = (assignmentId, planId) => {
  planToRemove.value = { assignmentId, planId }
  showRemovePlanDialog.value = true
}

const unassignPlan = async () => {
  if (!planToRemove.value) return

  try {
    await exercisePlanServices.unassignPlanFromAthlete(planToRemove.value.planId, athleteId.value)
    showRemovePlanDialog.value = false
    planToRemove.value = null
    showSuccess('Training plan unassigned successfully')
    await fetchAthleteAssignedPlans()
  } catch (err) {
    error.value = 'Unable to unassign plan. Please try again.'
  }
}

const goBack = () => {
  router.push({ name: 'coachDashboard' })  
}

const openAddGoalDialog = async () => {
  await loadCoachPlans()
  showAddGoalDialog.value = true
}

const closeAddGoalDialog = () => {
  showAddGoalDialog.value = false
  
  selectedPlanForGoal.value = null
  selectedExerciseForGoal.value = null
  exercisesFromPlan.value = []
  newGoal.value = {
    planId: null,
    exerciseId: null,
    exerciseName: '',
    targetValue: null,
    currentValue: 0,
    unit: 'reps',
    description: '',
    targetDate: '',
    timeframe: 'week'
  }
}

const createGoal = async () => {
  if (!selectedPlanForGoal.value) {
    error.value = 'Please select a training plan'
    return
  }
  
  if (!selectedExerciseForGoal.value) {
    error.value = 'Please select an exercise'
    return
  }
  
  if (!newGoal.value.targetValue || newGoal.value.targetValue <= 0) {
    error.value = 'Please enter a valid target value'
    return
  }
  
  try {
    const goalData = {
      athleteId: athleteId.value,
      title: autoGeneratedTitle.value,
      description: newGoal.value.description || `Goal for ${athlete.value.first_name} ${athlete.value.last_name}`,
      planId: selectedPlanForGoal.value,
      exerciseId: selectedExerciseForGoal.value,
      targetValue: newGoal.value.targetValue,
      currentValue: newGoal.value.currentValue,
      unit: newGoal.value.unit,
      targetDate: computedTargetDate.value
    }
    
    await goalServices.createGoalForAthlete(athleteId.value, goalData)
    await fetchAthleteGoals()
    closeAddGoalDialog()
    showSuccess('Goal created successfully')
    
  } catch (err) {
    if (err.response?.status === 401) {
      error.value = 'Session expired. Please log in again.'
      setTimeout(() => router.push('/'), 2000)
    } else {
      error.value = err.response?.data?.message || 'Unable to create goal. Please try again.'
    }
  }
}

const confirmDeleteGoal = (goal) => {
  goalToDelete.value = goal
  showDeleteGoalDialog.value = true
}

const deleteGoal = async () => {
  if (!goalToDelete.value) return

  try {
    await goalServices.deleteGoal(goalToDelete.value.id)
    await fetchAthleteGoals()
    showDeleteGoalDialog.value = false
    goalToDelete.value = null
    showSuccess('Goal deleted successfully')
  } catch (err) {
    if (err.response?.status === 401) {
      error.value = 'Session expired. Please log in again.'
      setTimeout(() => router.push('/'), 2000)
    } else {
      error.value = 'Unable to delete goal. Please try again.'
    }
  }
}

const getProgressColor = (progress) => {
  if (progress >= 75) return 'success'
  if (progress >= 50) return 'warning'
  return 'error'
}

const calculateProgress = (currentValue, targetValue) => {
  if (!targetValue || targetValue === 0) return 0
  return Math.min(Math.round((currentValue / targetValue) * 100), 100)
}

const formatDate = (date) => {
  if (!date) return ''
  const d = new Date(date)
  return d.toLocaleDateString('en-US', { month: '2-digit', day: '2-digit', year: 'numeric' })
}

const getInitials = (firstName, lastName) => {
  if (!firstName || !lastName) return '??'
  return `${firstName[0]}${lastName[0]}`.toUpperCase()
}

onMounted(async () => {
  user.value = Utils.getStore("user") || currentUser.value
  
  if (!user.value) {
    router.push('/')
  } else if (user.value.role !== 'coach') {
    error.value = 'Access denied. Coach role required.'
    setTimeout(() => router.push('/'), 2000)
  } else {
    await fetchAthleteData()
    await fetchAthleteGoals()
    await fetchAthleteResults()
    await loadExercises()
    await fetchAthleteAssignedPlans()
  }
})
</script>

<template>
  <v-container>
    <v-toolbar color="primary" dark class="mb-4">
      <v-btn icon @click="goBack">
        <v-icon>mdi-arrow-left</v-icon>
      </v-btn>
      <v-toolbar-title>Athlete Details</v-toolbar-title>
    </v-toolbar>

    <!-- Success Message -->
    <v-alert v-if="successMessage" type="success" class="mb-4" closable @click:close="successMessage = null">
      {{ successMessage }}
    </v-alert>

    <!-- Error Message -->
    <v-alert v-if="error" type="error" class="mb-4" closable @click:close="error = null">
      {{ error }}
    </v-alert>

    <!-- Loading State -->
    <div v-if="loading" class="text-center py-8">
      <v-progress-circular indeterminate color="primary"></v-progress-circular>
      <p class="mt-4">Loading athlete data...</p>
    </div>

    <!-- Content -->
    <div v-else>
      <!-- Athlete Header -->
      <v-card class="mb-4" elevation="2">
        <v-card-text>
          <div class="d-flex align-center mb-4">
            <v-avatar color="primary" size="64" class="mr-4">
              <span class="text-h5">{{ getInitials(athlete.first_name, athlete.last_name) }}</span>
            </v-avatar>
            <div>
              <h2 class="text-h4 font-weight-bold">{{ athlete.first_name }} {{ athlete.last_name }}</h2>
              <p class="text-grey">{{ athlete.email }}</p>
            </div>
          </div>

          <!-- Stats Row -->
          <v-row>
            <v-col cols="6" sm="3">
              <v-card color="grey-lighten-4">
                <v-card-text class="text-center">
                  <div class="text-caption text-grey-darken-1">Age</div>
                  <div class="text-h5 font-weight-bold">{{ athlete.age || '-' }}</div>
                </v-card-text>
              </v-card>
            </v-col>
            <v-col cols="6" sm="3">
              <v-card color="grey-lighten-4">
                <v-card-text class="text-center">
                  <div class="text-caption text-grey-darken-1">Gender</div>
                  <div class="text-h5 font-weight-bold">{{ athlete.gender || '-' }}</div>
                </v-card-text>
              </v-card>
            </v-col>
            <v-col cols="6" sm="3">
              <v-card color="grey-lighten-4">
                <v-card-text class="text-center">
                  <div class="text-caption text-grey-darken-1">Sport</div>
                  <div class="text-h5 font-weight-bold">{{ athlete.sport_type || '-' }}</div>
                </v-card-text>
              </v-card>
            </v-col>
            <v-col cols="6" sm="3">
              <v-card color="grey-lighten-4">
                <v-card-text class="text-center">
                  <div class="text-caption text-grey-darken-1">Total Workouts</div>
                  <div class="text-h5 font-weight-bold">{{ athlete.totalWorkouts || 0 }}</div>
                </v-card-text>
              </v-card>
            </v-col>
          </v-row>
        </v-card-text>
      </v-card>

      <!-- Tabs -->
      <v-card elevation="2">
        <v-tabs v-model="activeTab" bg-color="primary" dark>
          <v-tab value="goals">Goals</v-tab>
          <v-tab value="results">Results</v-tab>
          <v-tab value="plans">Plans</v-tab>
          <v-tab value="profile">Profile</v-tab>
        </v-tabs>

        <v-card-text>
          <v-window v-model="activeTab">
            <!-- Goals Tab -->
            <v-window-item value="goals">
              <div class="d-flex justify-space-between align-center mb-4">
                <div>
                  <h3 class="text-h6 font-weight-bold">Training Goals</h3>
                  <p class="text-caption text-grey">Set goals based on training plans</p>
                </div>
                <v-btn color="primary" @click="openAddGoalDialog">
                  <v-icon left>mdi-plus</v-icon>
                  Add Goal
                </v-btn>
              </div>

              <!-- Goals List -->
              <v-row v-if="goals.length > 0">
                <v-col v-for="goal in goals" :key="goal.id" cols="12">
                  <v-card elevation="1">
                    <v-card-text>
                      <div class="d-flex justify-space-between align-center mb-3">
                        <div>
                          <h4 class="text-h6 font-weight-bold">{{ goal.title }}</h4>
                          <div class="d-flex align-center mt-1">
                            <v-chip size="x-small" color="info" class="mr-2">
                              {{ goal.creatorRole || 'coach' }}
                            </v-chip>
                            <v-chip v-if="goal.exerciseName" size="x-small" color="secondary" class="mr-2">
                              {{ goal.exerciseName }}
                            </v-chip>
                            <v-chip v-if="goal.planName" size="x-small" color="primary">
                              {{ goal.planName }}
                            </v-chip>
                          </div>
                          <p class="text-caption text-grey mt-2">
                            Target: {{ goal.targetValue }} {{ goal.unit }} by {{ formatDate(goal.endDate) }}
                          </p>
                          <p class="text-body-2 mt-2">{{ goal.description }}</p>
                        </div>
                        <div class="d-flex align-center">
                          <v-chip size="small" :color="goal.status === 'active' ? 'success' : 'grey'" class="mr-2">
                            {{ goal.status }}
                          </v-chip>
                          <v-btn icon size="small" color="error" @click="confirmDeleteGoal(goal)">
                            <v-icon>mdi-delete</v-icon>
                          </v-btn>
                        </div>
                      </div>

                      <div class="mb-2">
                        <div class="d-flex justify-space-between text-caption mb-1">
                          <span>Current: {{ goal.currentValue }} {{ goal.unit }}</span>
                          <span class="font-weight-bold">{{ calculateProgress(goal.currentValue, goal.targetValue) }}%</span>
                        </div>
                        <v-progress-linear
                          :model-value="calculateProgress(goal.currentValue, goal.targetValue)"
                          :color="getProgressColor(calculateProgress(goal.currentValue, goal.targetValue))"
                          height="8"
                          rounded
                        ></v-progress-linear>
                      </div>
                    </v-card-text>
                  </v-card>
                </v-col>
              </v-row>

              <v-alert v-else type="info" variant="tonal">
                No goals set yet. Click "Add Goal" to create one based on a training plan.
              </v-alert>
            </v-window-item>

            <!-- Results Tab -->
            <v-window-item value="results">
              <div class="mb-4">
                <h3 class="text-h6 font-weight-bold">Workout Results</h3>
                <p class="text-caption text-grey">Complete workout history</p>
              </div>

              <v-table v-if="workoutResults.length > 0">
                <thead>
                  <tr>
                    <th class="text-left font-weight-bold">Date</th>
                    <th class="text-left font-weight-bold">Exercise</th>
                    <th class="text-left font-weight-bold">Sets</th>
                    <th class="text-left font-weight-bold">Reps</th>
                    <th class="text-left font-weight-bold">Weight</th>
                    <th class="text-left font-weight-bold">Notes</th>
                  </tr>
                </thead>
                <tbody>
                  <tr v-for="result in workoutResults" :key="result.id">
                    <td>{{ formatDate(result.performedDate) }}</td>
                    <td>{{ result.exerciseName }}</td>
                    <td>{{ result.setsDone || '-' }}</td>
                    <td>{{ result.repsDone || '-' }}</td>
                    <td>{{ result.weightUsed || '-' }}</td>
                    <td>{{ result.notes || '-' }}</td>
                  </tr>
                </tbody>
              </v-table>

              <v-alert v-else type="info" variant="tonal">
                No workout results yet.
              </v-alert>
            </v-window-item>

            <!-- Plans Tab -->
            <v-window-item value="plans">
              <div class="d-flex justify-space-between align-center mb-4">
                <div>
                  <h3 class="text-h6 font-weight-bold">Assigned Training Plans</h3>
                  <p class="text-caption text-grey">Manage athlete's training programs</p>
                </div>
                <v-btn color="primary" @click="openAssignPlanDialog">
                  <v-icon left>mdi-plus</v-icon>
                  Assign Plan
                </v-btn>
              </div>

              <v-row v-if="athleteAssignedPlans.length > 0">
                <v-col v-for="assignment in athleteAssignedPlans" :key="assignment.assignmentId" cols="12">
                  <v-card elevation="1">
                    <v-card-text>
                      <div class="d-flex justify-space-between align-center">
                        <div class="flex-grow-1">
                          <div class="d-flex align-center mb-2">
                            <h4 class="text-h6 font-weight-bold mr-3">{{ assignment.plan.name }}</h4>
                            <v-chip size="small" :color="assignment.status === 'active' ? 'success' : 'grey'">
                              {{ assignment.status }}
                            </v-chip>
                          </div>
                          <p class="text-caption text-grey">
                            Assigned: {{ formatDate(assignment.assignedDate) }} • 
                            {{ assignment.plan.exerciseCount }} exercises
                          </p>
                          <p class="text-body-2 mt-2">{{ assignment.plan.description || 'No description' }}</p>
                        </div>
                        <v-btn 
                          icon 
                          size="small" 
                          color="error" 
                          @click="confirmUnassignPlan(assignment.assignmentId, assignment.plan.id)"
                          class="ml-4"
                        >
                          <v-icon>mdi-delete</v-icon>
                        </v-btn>
                      </div>
                    </v-card-text>
                  </v-card>
                </v-col>
              </v-row>

              <v-alert v-else type="info" variant="tonal">
                No plans assigned yet. Click "Assign Plan" to get started.
              </v-alert>
            </v-window-item>

            <!-- Profile Tab -->
            <v-window-item value="profile">
              <div class="mb-4">
                <h3 class="text-h6 font-weight-bold">Athlete Profile</h3>
                <p class="text-caption text-grey">Personal information and training notes</p>
              </div>

              <v-row>
                <v-col cols="12" md="6">
                  <v-list>
                    <v-list-item>
                      <v-list-item-title class="font-weight-bold">Age</v-list-item-title>
                      <v-list-item-subtitle>{{ athlete.age || '-' }}</v-list-item-subtitle>
                    </v-list-item>
                    <v-divider></v-divider>
                    
                    <v-list-item>
                      <v-list-item-title class="font-weight-bold">Gender</v-list-item-title>
                      <v-list-item-subtitle>{{ athlete.gender || '-' }}</v-list-item-subtitle>
                    </v-list-item>
                    <v-divider></v-divider>
                    
                    <v-list-item>
                      <v-list-item-title class="font-weight-bold">Sport Type</v-list-item-title>
                      <v-list-item-subtitle>{{ athlete.sport_type || '-' }}</v-list-item-subtitle>
                    </v-list-item>
                    <v-divider></v-divider>
                    
                    <v-list-item>
                      <v-list-item-title class="font-weight-bold">Team</v-list-item-title>
                      <v-list-item-subtitle>{{ athlete.team || '-' }}</v-list-item-subtitle>
                    </v-list-item>
                  </v-list>
                </v-col>

                <v-col cols="12" md="6">
                  <v-list>
                    <v-list-item>
                      <v-list-item-title class="font-weight-bold">Bio</v-list-item-title>
                      <v-list-item-subtitle>{{ athlete.bio || '-' }}</v-list-item-subtitle>
                    </v-list-item>
                  </v-list>
                </v-col>
              </v-row>
            </v-window-item>
          </v-window>
        </v-card-text>
      </v-card>

      <!-- Add Goal Dialog -->
      <v-dialog v-model="showAddGoalDialog" max-width="700px" persistent>
        <v-card>
          <v-card-title class="bg-primary">
            <div class="d-flex justify-space-between align-center">
              <div>
                <div class="text-h5">Create Training Goal</div>
                <div class="text-caption">Set a goal based on an exercise plan</div>
              </div>
              <v-btn icon variant="text" @click="closeAddGoalDialog">
                <v-icon>mdi-close</v-icon>
              </v-btn>
            </div>
          </v-card-title>

          <v-card-text class="pt-4">
            <v-form>
              <!-- Step 1: Select Training Plan -->
              <div class="mb-4">
                <div class="text-subtitle-1 font-weight-bold mb-2">
                  <v-icon left color="primary">mdi-numeric-1-circle</v-icon>
                  Select Training Plan
                </div>
                <v-select
                  v-model="selectedPlanForGoal"
                  :items="coachPlans"
                  item-title="name"
                  item-value="id"
                  label="Training Plan *"
                  variant="outlined"
                  @update:model-value="onPlanSelected"
                >
                  <template v-slot:item="{ props, item }">
                    <v-list-item v-bind="props">
                      <template v-slot:subtitle>
                        <small>{{ item.raw.exercises }} exercises</small>
                      </template>
                    </v-list-item>
                  </template>
                </v-select>
              </div>

              <!-- Step 2: Select Exercise -->
              <div class="mb-4" v-if="selectedPlanForGoal">
                <div class="text-subtitle-1 font-weight-bold mb-2">
                  <v-icon left color="primary">mdi-numeric-2-circle</v-icon>
                  Select Exercise
                </div>
                <v-select
                  v-model="selectedExerciseForGoal"
                  :items="exercisesFromPlan"
                  item-title="name"
                  item-value="id"
                  label="Exercise *"
                  variant="outlined"
                  :loading="loadingExercises"
                  :disabled="exercisesFromPlan.length === 0"
                >
                  <template v-slot:item="{ props, item }">
                    <v-list-item v-bind="props">
                      <template v-slot:subtitle>
                        <small>{{ item.raw.muscleGroup || 'Full Body' }}</small>
                      </template>
                    </v-list-item>
                  </template>
                </v-select>
              </div>

              <!-- Step 3: Set Target -->
              <div class="mb-4" v-if="selectedExerciseForGoal">
                <div class="text-subtitle-1 font-weight-bold mb-2">
                  <v-icon left color="primary">mdi-numeric-3-circle</v-icon>
                  Set Target
                </div>
                
                <v-row>
                  <v-col cols="6">
                    <v-text-field
                      v-model.number="newGoal.targetValue"
                      label="Target Value *"
                      type="number"
                      variant="outlined"
                      min="1"
                      step="0.1"
                    ></v-text-field>
                  </v-col>
                  <v-col cols="6">
                    <v-select
                      v-model="newGoal.unit"
                      :items="unitOptions"
                      item-title="title"
                      item-value="value"
                      label="Unit *"
                      variant="outlined"
                    ></v-select>
                  </v-col>
                </v-row>

                <v-alert v-if="autoGeneratedTitle" type="info" variant="tonal" density="compact" class="mb-3">
                  <strong>Goal:</strong> {{ autoGeneratedTitle }}
                </v-alert>
              </div>

              <!-- Step 4: Timeframe -->
              <div class="mb-4" v-if="autoGeneratedTitle">
                <div class="text-subtitle-1 font-weight-bold mb-2">
                  <v-icon left color="primary">mdi-numeric-4-circle</v-icon>
                  Timeframe
                </div>
                
                <v-select
                  v-model="newGoal.timeframe"
                  :items="timeframeOptions"
                  item-title="title"
                  item-value="value"
                  label="Timeframe *"
                  variant="outlined"
                  class="mb-3"
                ></v-select>

                <v-text-field
                  v-if="newGoal.timeframe === 'custom'"
                  v-model="newGoal.targetDate"
                  label="Custom Target Date"
                  type="date"
                  variant="outlined"
                ></v-text-field>

                <v-alert type="success" variant="tonal" density="compact">
                  <strong>Deadline:</strong> {{ formatDate(computedTargetDate) }}
                </v-alert>
              </div>

              <!-- Optional: Description -->
              <div v-if="autoGeneratedTitle">
                <v-textarea
                  v-model="newGoal.description"
                  label="Additional Notes (Optional)"
                  variant="outlined"
                  rows="2"
                  placeholder="Any specific instructions or notes for this goal..."
                ></v-textarea>
              </div>
            </v-form>
          </v-card-text>

          <v-card-actions>
            <v-spacer></v-spacer>
            <v-btn variant="text" @click="closeAddGoalDialog">Cancel</v-btn>
            <v-btn 
              color="primary" 
              @click="createGoal"
              :disabled="!selectedPlanForGoal || !selectedExerciseForGoal || !newGoal.targetValue"
            >
              Create Goal
            </v-btn>
          </v-card-actions>
        </v-card>
      </v-dialog>

      <!-- Assign Plan Dialog -->
      <v-dialog v-model="showAssignPlanDialog" max-width="600px">
        <v-card>
          <v-card-title class="bg-primary">
            <div class="d-flex justify-space-between align-center">
              <span class="text-h5">Assign Training Plan</span>
              <v-btn icon variant="text" @click="closeAssignPlanDialog">
                <v-icon>mdi-close</v-icon>
              </v-btn>
            </div>
          </v-card-title>

          <v-card-text class="pt-4">
            <p class="text-caption text-grey mb-4">
              Select a training plan to assign to {{ athlete.first_name }} {{ athlete.last_name }}
            </p>

            <v-select
              v-model="selectedPlanId"
              :items="availablePlans"
              item-title="name"
              item-value="id"
              label="Training Plan *"
              variant="outlined"
            >
              <template v-slot:item="{ props, item }">
                <v-list-item v-bind="props">
                  <template v-slot:subtitle>
                    <small>{{ item.raw.exercises }} exercises</small>
                  </template>
                </v-list-item>
              </template>
            </v-select>
          </v-card-text>

          <v-card-actions>
            <v-spacer></v-spacer>
            <v-btn variant="text" @click="closeAssignPlanDialog">Cancel</v-btn>
            <v-btn color="primary" @click="assignPlan" :disabled="!selectedPlanId">Assign Plan</v-btn>
          </v-card-actions>
        </v-card>
      </v-dialog>

      <!-- Remove Plan Confirmation Dialog -->
      <v-dialog v-model="showRemovePlanDialog" max-width="500px">
        <v-card>
          <v-card-title class="bg-warning text-white">
            <v-icon left color="white">mdi-alert</v-icon>
            Remove Training Plan
          </v-card-title>

          <v-card-text class="pt-6">
            <div class="text-center">
              <v-icon size="64" color="warning" class="mb-4">mdi-clipboard-remove</v-icon>
              <p class="text-h6 mb-2">Are you sure you want to remove this training plan?</p>
              <p class="text-body-2 text-grey">This will unassign the plan from {{ athlete.first_name }} {{ athlete.last_name }}.</p>
            </div>
          </v-card-text>

          <v-card-actions class="px-6 pb-6">
            <v-spacer></v-spacer>
            <v-btn variant="text" @click="showRemovePlanDialog = false; planToRemove = null">
              Cancel
            </v-btn>
            <v-btn color="warning" @click="unassignPlan">
              <v-icon left>mdi-close-circle</v-icon>
              Remove Plan
            </v-btn>
          </v-card-actions>
        </v-card>
      </v-dialog>

      <!-- Delete Goal Confirmation Dialog -->
      <v-dialog v-model="showDeleteGoalDialog" max-width="500px">
        <v-card>
          <v-card-title class="bg-error text-white">
            <v-icon left color="white">mdi-alert-circle</v-icon>
            Delete Goal
          </v-card-title>

          <v-card-text class="pt-6">
            <div v-if="goalToDelete" class="text-center">
              <v-icon size="64" color="error" class="mb-4">mdi-flag-remove</v-icon>
              <p class="text-h6 mb-2">Are you sure you want to delete this goal?</p>
              <p class="text-body-1 font-weight-bold">{{ goalToDelete.exercise_name }}</p>
              <p class="text-caption text-grey mb-2">Target: {{ goalToDelete.target_value }} {{ goalToDelete.unit }}</p>
              <v-alert type="warning" variant="tonal" class="mt-4">
                <strong>Warning:</strong> This action cannot be undone. All progress tracking for this goal will be permanently deleted.
              </v-alert>
            </div>
          </v-card-text>

          <v-card-actions class="px-6 pb-6">
            <v-spacer></v-spacer>
            <v-btn variant="text" @click="showDeleteGoalDialog = false; goalToDelete = null">
              Cancel
            </v-btn>
            <v-btn color="error" @click="deleteGoal">
              <v-icon left>mdi-delete</v-icon>
              Delete Goal
            </v-btn>
          </v-card-actions>
        </v-card>
      </v-dialog>
    </div>
  </v-container>
</template>